name: travelhive
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  sign_in_button: ^3.0.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  flutter_bloc: ^8.1.6
  top_snackbar_flutter: ^3.1.0
  intl: ^0.20.1
  smooth_page_indicator: ^1.0.0
  flutter_screenutil: ^5.9.3
  persistent_bottom_nav_bar_v2: ^5.3.1
  image_picker: ^1.1.2
  mime: ^2.0.0
  google_maps_flutter: ^2.10.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true